### ISSUE TITLE
nothing in blade

### ISSUE THREAD

**Issue by Zdeshniy89** [julles/laravel-highcharts#1]
hello. in controller:
`public function index()
    { 
        
$charts = [

    'chart' => ['type' => 'column'],
    'title' => ['text' => 'fruit Consumption'],
    'xAxis' => [
        'categories' => ['apples' , 'bananas'],
    ],
    'yAxis' => [
        'title' => [
            'text' => 'Fruit Eaten'
        ]
    ],
    'series' => [
        [
            'name' => 'Reza',
            'data' => [1,2]
        ],
        [
            'name' => 'Kika',
            'data' => [2,4]
        ],
    ]
];
return view('home', ['charts' => $charts]);
    }`

in home.blade.php 
`{!! Chart::display("111", $charts) !!}`

and nothing for output. but if all this code in controller with output, that highcharts shows.

**Comment by julles** [comment]
check in your view, are already installed jquery?

**Comment by julles** [comment]
try this 
```sh
{!! Chart::display("111", $charts , ['jquery.js' => false , 'highcharts.js' => true]) !!}
```
