### ISSUE TITLE
Chart Display on PDF

### ISSUE THREAD

**Issue by zahidaziz16** [julles/laravel-highcharts#2]
How to view generated chart on pdf?

**Comment by julles** [comment]
I've added a feature button export
update package : 
```sh
composer update muhamadrezaar/highcharts
```
by default, the download button Highcharts existing
![alt tag](http://s7.postimg.org/rnsf0lcwr/chart_export.png)

**Comment by zahidaziz16** [comment]
Thanks, but my flow goes like this, from laravel controller I send a json responses to pdf view which the highchart is included together inside the json response.. Im planning to convert the generated svg chart into base64 image and show it at the pdf view.. Is there any best way I could make this happen? Thanks

**Comment by zahidaziz16** [comment]
How I can get its svg file at controller?

**Comment by julles** [comment]
sorry I'm working right now, maybe later tonight (Indonesian time) I will try to find a solution for it :)

**Comment by julles** [comment]
I've added a chat feature to svg
example : 

```sh
<?php echo Chart::display("id", $charts,['format' => 'svg']); ?>
```
dont forget update package

**Comment by zahidaziz16** [comment]
Hi it's great reza..! yet another thing, I am not able to convert to base64 and embed it to pdf viewer.. is the format 'svg' can be changed like 'pdf'/'png'/'jpeg'?

**Comment by julles** [comment]
A. Create route only display highchart
```sh
Route::get('base64' , function(){
echo Chart::display("myId", $charts,['format' => 'base64']);
});
```
B. create default route 
```sh
Route::get('result',function(){
    $base64= file_get_contents(url('base64'));
    // what do you want to manipulation base64 code ,generate or process anything here
});
```
C. Dont forget update package

**Comment by julles** [comment]
Why created two routes?
because helper Chart::display() returning javascript script
The second route taking existing content on Route 1, and then be made variable using file_get_contents().

sorry my english is bad hahaha

**Comment by xeroky** [comment]
it is possible to save the chart as an image and then put it in pdf?

**Comment by julles** [comment]
read my comment above :)

sorry my english is bad :D

**Comment by xeroky** [comment]
I read it

I need create a pdf with multiple charts.
My idea is:
- Make and save all charts, with mysql values, in a temporary server folder.
- Make pdf from a view with the images of charts saved in folder
- Download pdf
- Delete folder

All in a Laravel controller. So need export charts.

**Comment by xeroky** [comment]
any idea?

**Comment by julles** [comment]
A. Create route only display highchart
``` sh
Route::get('base64' , function(){
echo Chart::display("myId", $charts,['format' => 'base64']);
});
```
B. create default route
``` sh
Route::get('result',function(){
    $base64= file_get_contents(url('base64'));
    // what do you want to manipulation base64 code ,generate or process anything here
});
```

the above script does not work?

**Comment by plicas** [comment]
@zahidaziz16 did u figure a way to do this ?
