### ISSUE TITLE
Chart not found

### ISSUE THREAD

**Issue by xeroky** [julles/laravel-highcharts#3]
Hi,

I have a problem:
Class 'App\Http\Controllers\Chart' not found

on line
echo Chart::display("id-highchartsnya", $charts);

inside a PdfController

Help me please?

**Comment by julles** [comment]
may I see your controller and an error message?

**Comment by xeroky** [comment]
Hi,

PdfController
---------

<?php

namespace App\Http\Controllers;



use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PdfController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $charts = [

            'chart' => ['type' => 'column'],
            'title' => ['text' => 'fruit Consumption'],
            'xAxis' => [
                'categories' => ['apples' , 'bananas'],
            ],
            'yAxis' => [
                'title' => [
                    'text' => 'Fruit Eaten'
                ]
            ],
            'series' => [
                [
                    'name' => 'Reza',
                    'data' => [1,2]
                ],
                [
                    'name' => 'Kika',
                    'data' => [2,4]
                ],
            ]
        ];

        echo Chart::display("id-highchartsnya", $charts);


In 'providers'

Oblagio\Highcharts\Provider::class,


In 'aliases'

'Chart'     => Oblagio\Highcharts\Facade::class,


Error:

FatalErrorException in PdfController.php line 45: Class
'App\Http\Controllers\Chart' not found

   1. in PdfController.php line 45
   2. at FatalErrorException->__construct() in HandleExceptions.php line 133
   3. at HandleExceptions->fatalExceptionFromError() in HandleExceptions.php
   line 118
   4. at HandleExceptions->handleShutdown() in HandleExceptions.php line 0


Salut!
Marc

2016-08-04 12:16 GMT+02:00 Muhamad Reza Abdul Rohim <
notifications@github.com>:

**Comment by xeroky** [comment]
Hi,

The question is: Why seeks class 'chart' in 'Controllers' folder?
Seems facade or alias not recorded well.

Salut!
Marc

2016-08-04 16:57 GMT+02:00 Muhamad Reza Abdul Rohim <
notifications@github.com>:

**Comment by julles** [comment]
```sh
echo \Chart::display("id-highchartsnya", $charts);
```
use the backslash '\'

or import Chart class 
``` sh
use Chart;
```

**Comment by xeroky** [comment]
Thanks! work fine!
