### ISSUE TITLE
JS Expressions

### ISSUE THREAD

**Issue by keithslater** [julles/laravel-highcharts#5]
Hello,

How can you write javascript expressions with this? For example - 

If you wanted to change the tooltip formatter - 
     `$chart['tooltips']['formatter'] = "this.series.name";`

Will output 
    `{"formatter":"this.series.name"}`

When it should output 
    `{"formatter": this.series.name }`

However, there isn't a way to tell it that what I want to output is Javascript.

**Comment by dingman** [comment]
+1

**Comment by dingman** [comment]
@julles any updates on this?

**Comment by julles** [comment]
sorry, lately I'm busy for doing my office project

maybe this week I'll update

**Comment by julles** [comment]
hi @dingman I've updated the script
use the latest version 
``` sh
composer require muhamadrezaar/highcharts:dev-master
```
JS Expressions : 
``` sh
->xaxis([
        'categories' => [
            'Messi',
            'CR7',
            'Bambang Pamungkas',
            'Del Piero',
        ],
        'labels'     => [
            'rotation'  => 15,
            'align'     => 'top',
            'formatter' => 'startJs:function(){return this.value + " (Footbal Player)"}:endJs',
        ],
    ])

```

read more in readme.md

**Comment by dingman** [comment]
Great, thank you!
