### ISSUE TITLE
Pie

### ISSUE THREAD

**Issue by xeroky** [julles/laravel-highcharts#6]
Hi,

I can not do a 'pie' graphic. Do you have documentation to make different types of charts?

Thanks,

**Comment by erick-jeronimo** [comment]
Same here. Any solution?

**Comment by User-Shalom** [comment]
@julles Any solution for pie chart? 
How can write this code as array in my Controller color: (Highcharts.theme && `Highcharts.theme.contrastTextColor) || `'black'`
`

**Comment by julles** [comment]
hi all
I've updated the script. use the latest version 
``` sh
composer require muhamadrezaar/highcharts:dev-master
```
JS Expressions : 
``` sh
->xaxis([
        'categories' => [
            'Messi',
            'CR7',
            'Bambang Pamungkas',
            'Del Piero',
        ],
        'labels'     => [
            'rotation'  => 15,
            'align'     => 'top',
            'formatter' => 'startJs:function(){return this.value + " (Footbal Player)"}:endJs',
        ],
    ])

```

read more in readme.md
