### ISSUE TITLE
Display more than 1 chart at the same time

### ISSUE THREAD

**Issue by swinyx** [julles/laravel-highcharts#7]
For some reason, this doesnt work if you try to add 2 or more charts to the page

**Comment by julles** [comment]
``` sh
{!! Chart::display("chart1", $charts) !!}

{!! Chart::display("chart2", $charts) !!}

```

are you unsuccessful using this code?

**Comment by Crzech** [comment]
Yes, the problem is 'cause method "display" always load highcharts libraries, should be loaded somewhere in the view only one time.

**Comment by fireworkstech** [comment]
Any update on this ?

**Comment by fireworkstech** [comment]
<?=Chart::display("id-highchartsnya", $chart)?>

<?=Chart::display('id-highcharx', $payment_type_chart_amount_in, ['jquery.js' => false , 'highcharts.js' => false,'exporting.js'=> false,'format' => 'chart'])?>

use Like this

**Comment by fireworkstech** [comment]
`<?=Chart::display("id-highchartsnya", $chart)?>

<?=Chart::display('id-highcharx', $payment_type_chart_amount_in, ['jquery.js' => false , 'highcharts.js' => false,'exporting.js'=> false,'format' => 'chart'])?>`


This will help showing multiple charts on a same page

**Comment by fireworkstech** [comment]
```
{!! Chart::display("id-highchartsnya", $chart) !!}

{!! Chart::display('id-highcharx', $payment_type_chart_amount_in, ['jquery.js' => false , 'highcharts.js' => false,'exporting.js'=> false,'format' => 'chart']) !!}
```

This will help showing multiple charts on a same page

**Comment by julles** [comment]
hai @fireworkstech 

I have updated the script

please install the latest version

```sh
composer require muhamadrezaar / highcharts: dev-master
```

read more on readme.md for more information
